// <auto-generated />
using System;
using GeneoAPI_1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeneoAPI_1.Migrations
{
    [DbContext(typeof(GeneoDbContext))]
    partial class GeneoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeneoAPI_1.Models.GeneoTree", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortName")
                        .HasColumnType("longtext");

                    b.HasKey("Uuid");

                    b.ToTable("geneo_tree");

                    b.HasComment("A root of every genealogy");
                });

            modelBuilder.Entity("GeneoAPI_1.Models.Person", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("BirthDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GeneoTreeUuid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Uuid");

                    b.HasIndex("GeneoTreeUuid");

                    b.ToTable("person");

                    b.HasComment("Represents any individual in the system");
                });

            modelBuilder.Entity("GeneoAPI_1.Models.Person", b =>
                {
                    b.HasOne("GeneoAPI_1.Models.GeneoTree", "GeneoTree")
                        .WithMany("Persons")
                        .HasForeignKey("GeneoTreeUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneoTree");
                });

            modelBuilder.Entity("GeneoAPI_1.Models.GeneoTree", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
